//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int CommentId { get; set; }
        public int NoteId { get; set; }
        public int UserId { get; set; }
        public string Text { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> UnderCommentId { get; set; }
    
        public virtual Notes Notes { get; set; }
        public virtual Users Users { get; set; }
    }
}
